### ISSUE TITLE
Error executing batch_writer

### ISSUE THREAD

**Issue by dpalme3160** [aws-samples/csv-to-dynamodb#11]
The Lambda function worked great for the first two imports, now when I'm attempting to import a csv with 70 items it's throwing this error.

Here are the log entries:

2022-06-23T21:05:40.424-05:00CopySTART RequestId: aa9ba096-2802-44e5-b66d-2ec2b83bf54f Version: $LATEST | START RequestId: aa9ba096-2802-44e5-b66d-2ec2b83bf54f Version: $LATEST

2022-06-23T21:05:40.521-05:00CopyError executing batch_writer | Error executing batch_writer

2022-06-23T21:05:40.523-05:00CopyEND RequestId: aa9ba096-2802-44e5-b66d-2ec2b83bf54f | END RequestId: aa9ba096-2802-44e5-b66d-2ec2b83bf54f

2022-06-23T21:05:40.523-05:00CopyREPORT RequestId: aa9ba096-2802-44e5-b66d-2ec2b83bf54f	Duration: 97.66 ms	Billed Duration: 98 ms	Memory Size: 3008 MB	Max Memory Used: 78 MB	Init Duration: 498.80 ms | REPORT RequestId: aa9ba096-2802-44e5-b66d-2ec2b83bf54f Duration: 97.66 ms Billed Duration: 98 ms Memory Size: 3008 MB Max Memory Used: 78 MB Init Duration: 498.80

This is the Lambda code I'm using:
`
import json
import boto3
import os
import csv
import codecs
import sys

s3 = boto3.resource('s3')
dynamodb = boto3.resource('dynamodb')

bucket = os.environ['bucket']
key = os.environ['key']
tableName = os.environ['table']

def lambda_handler(event, context):

   #get() does not store in memory
   try:
       obj = s3.Object(bucket, key).get()['Body']
   except:
       print("S3 Object could not be opened. Check environment variable. ")
   try:
       table = dynamodb.Table(tableName)
   except:
       print("Error loading DynamoDB table. Check if table was created correctly and environment variable.")

   batch_size = 100
   batch = []

   #DictReader is a generator; not stored in memory
   for row in csv.DictReader(codecs.getreader('utf-8')(obj)):
      if len(batch) >= batch_size:
         write_to_dynamo(batch)
         batch.clear()

      batch.append(row)

   if batch:
      write_to_dynamo(batch)

   return {
      'statusCode': 200,
      'body': json.dumps('Uploaded to DynamoDB Table')
   }

def write_to_dynamo(rows):
   try:
      table = dynamodb.Table(tableName)
   except:
      print("Error loading DynamoDB table. Check if table was created correctly and environment variable.")

   try:
      with table.batch_writer() as batch:
         for i in range(len(rows)):
            batch.put_item(
               Item=rows[i]
            )
   except:
      print("Error executing batch_writer")`

Here is the file we are attempting to upload:

[Upload.csv](https://github.com/aws-samples/csv-to-dynamodb/files/8972681/Upload.csv)

**Comment by ChenMorad** [comment]
same issue here lambda is successful with the return of Error executing batch_writer

**Comment by dpalme3160** [comment]
I can't believe that in six days, nobody has responded to this.

**Comment by antpas** [comment]
Thanks for your feedback. We updated the code to provide more descriptive errors. Additionally, we fixed a utf-8 codec issue which was causing issues with column name. We have also tested using your csv example above and see that it is now working.
