### ISSUE TITLE
batch-size = 100 and doc says it's limit is 25

### ISSUE THREAD

**Issue by guilherme** [aws-samples/csv-to-dynamodb#3]
Hello,

Could you explain how this example would work given that it says in the docs that the limit is 25 request per batch, but here the code says batch_size = 100 ?

https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_BatchWriteItem.html

Am I missing something?

Thank you,

**Comment by antpas** [comment]
Hi guilherme,

We are using DynamoDB.Table.batch_writer() in boto3. This method returns a handle to a batch writer object that will automatically handle buffering and sending items in batches. Hence, why we can iterate over 100 rows at a time and write them to the table. Read more about it here:

https://boto3.amazonaws.com/v1/documentation/api/latest/guide/dynamodb.html#batch-writing
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/dynamodb.html#DynamoDB.Table.batch_writer

Thanks!
