### ISSUE TITLE
Doesn't work with existing table

### ISSUE THREAD

**Issue by jwanga** [aws-samples/csv-to-dynamodb#4]
Thank you for this solution. However, Is there a way to make it work with existing tables? I don't want to have to delete my existing data.

**Comment by CR1AT0RS** [comment]
Same issue here. Is it possible to import data into existing table?

**Comment by C2BB** [comment]
Modify the template and delete the DynamoDB resource.

**Comment by robmoores** [comment]
For working with existing resources please see these two articles:  https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resource-import.html https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resource-import-existing-stack.html

**Comment by gabrielfernandes-codes** [comment]
If anyone in the future needs a reference of @C2BB change, it is the following: https://github.com/fernandesGabriel/csv-to-dynamodb/commit/79822963c27d42535cefd2ea95ce9416d7576fc8

**Comment by antpas** [comment]
See @fernandesGabriel's fork for using with existing tables. This example only supports new tables.
