### ISSUE TITLE
Template Format Error

### ISSUE THREAD

**Issue by Ivanchigo** [aws-samples/csv-to-dynamodb#6]
When loading the template in cloudformation and pressing the next button, the following error is generated:

Template format error: YAML not well-formed. (line 96, column 65)

I have tried to review the error but my ignorance does not allow me to solve it

I appreciate that this error can be fixed.

**Comment by Ivanchigo** [comment]
When opening the template in the designer the error is the following:

Cannot convert the template because of an error :: end of the stream or a document separator is expected at line 96, column 65: ... e "content =" {& quot; version & quot ;: & quot; 4 & quot ;, & quot; rollouts & quot;. .. ^

The template interprets it as JSON, not as YAML and does not allow converting it

**Comment by robmoores** [comment]
The template is a JSON file not YAML
