### ISSUE TITLE
CSV files created in Excel fail with "BatchWriteItem operation: The provided key element does not match the schema" error

### ISSUE THREAD

**Issue by dgwalters** [aws-samples/csv-to-dynamodb#9]
The provided Lambda function uses the `utf-8` codec for csv.DictReader which means the first column name is prepended with `u'\ufeff'` and therefore doesn't match the Partition Key name. The Lambda reports as successfully running but logs the `Error executing batch_writer` error to CloudWatch Logs.

**Comment by dgwalters** [comment]
Pull Request #10

**Comment by antpas** [comment]
Merged utf fix and added more descriptive error handling.
